repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/biomejs/pre-commit
    rev: v0.5.0
    hooks:
      - id: biome-check
        args: [ --config-path=./biome.json ]
        additional_dependencies: ["@biomejs/biome@1.9.4"]

  - repo: local
    hooks:
      - id: cargo-clippy
        name: Cargo Clippy
        description: Run Rust linter on staged files
        entry: bash -c 'cd src-tauri && cargo clippy -- -D warnings'
        language: system
        pass_filenames: false
        types: [file]
        files: ^src-tauri/src/.*\.rs$

      - id: cargo-fmt
        name: Cargo Format
        description: Run Rust formatter on staged files
        entry: bash -c 'cd src-tauri && cargo fmt'
        language: system
        pass_filenames: false
        types: [file]
        files: ^src-tauri/src/.*\.rs$
