// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function StartRecording():Promise<main.Result>;

export function StopRecording():Promise<main.Result>;
