// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWhisperSettings() {
  return window['go']['main']['App']['GetWhisperSettings']();
}

export function ListAvailableModels() {
  return window['go']['main']['App']['ListAvailableModels']();
}

export function SaveWhisperSettings(arg1) {
  return window['go']['main']['App']['SaveWhisperSettings'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
