// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartRecording():Promise<boolean>;

export function StopRecording():Promise<boolean>;
