// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';

export function GetSettings():Promise<main.DictatorSettings>;

export function ListAvailableModels():Promise<Array<app.ModelInfo>>;

export function SaveSettings(arg1:main.DictatorSettings):Promise<main.Result>;

export function StartRecording():Promise<main.Result>;

export function StopRecording():Promise<main.Result>;
